In [1]:
import pandas as pd
import numpy as np
from pathlib import Path 
import os 
import matplotlib.pyplot as plt

In [2]:
os.getcwd()

'c:\\Users\\chodu\\Desktop\\midterm2026\\project\\source_code'

In [3]:
pathb = os.path.abspath(os.path.join(os.getcwd(), '..'))
pathb = os.path.join(pathb, "data", "raw", "billa_prices.csv")

billa = pd.read_csv(pathb)

In [4]:
pathl = os.path.abspath(os.path.join(os.getcwd(), '..'))
pathl = os.path.join(pathl, "data", "raw", "lidl_prices.csv")

lidl = pd.read_csv(pathl)

In [5]:
lidl

,item,title,price_czk,packaging,price_per_unit
0,ovesne_vlocky,Ovesné vločky hrub,11.9,500 g,0.023800
1,mleko,"Trvanlivé mléko 1,5%",12.9,1 l,0.012900
2,banany,NaN,NaN,NaN,NaN
3,chleb,Dřevorubecký chléb,23.9,405 g,0.059012
4,maslo,Perla Margarín s máslovou příchutí 39% tuku,34.9,450 g,0.077556
5,vejce,NaN,NaN,NaN,NaN
6,spagety,Špagety,11.9,500 g,0.023800
7,pesto,NaN,NaN,NaN,NaN
8,ryze,NaN,NaN,NaN,NaN
9,mrazena_zelenina,NaN,NaN,NaN,NaN
10,kureci_prsa,BIO Kuřecí prsní řízky,59.9,Dostupné pouze ve vybraných prodejnách,NaN
11,tofu,NaN,NaN,NaN,NaN
12,cibule,NaN,NaN,NaN,NaN
13,cesnek,Česnek,39.9,NaN,NaN
14,syr_eidam,PILOS Eidam,9.9,NaN,NaN
15,tunak,Tuňák žlutoploutvý,39.9,cena za 100 g,0.399000
16,jogurt,Bílý jogurt,17.9,300 g,0.059667
17,kava,NaN,NaN,NaN,NaN
18,ovesny_napoj,NaN,NaN,NaN,NaN
19,sojovy_napoj,NaN,NaN,NaN,NaN
20,repkovy_olej,Řepkový olej,34.9,1 l,0.034900
21,cervena_cocka,NaN,NaN,NaN,NaN
22,rajcatova_omacka,NaN,NaN,NaN,NaN
23,paprika,NaN,NaN,NaN,NaN

In [6]:
pathr = os.path.abspath(os.path.join(os.getcwd(), '..'))
pathr = os.path.join(pathr, "data", "raw", "rohlik_prices.csv")

rohlik = pd.read_csv(pathr)

In [7]:
pathk = os.path.abspath(os.path.join(os.getcwd(), '..'))
pathk = os.path.join(pathk, "data", "raw", "kosik_prices.csv")

kosik = pd.read_csv(pathk)

In [8]:
billa = billa.add_prefix("billa_")
lidl = lidl.add_prefix("lidl_")
kosik = kosik.add_prefix("kosik_")
rohlik = rohlik.add_prefix("rohlik_")

In [9]:
billa = billa.rename(columns={"billa_item": "item"})
lidl = lidl.rename(columns={"lidl_item": "item"})
kosik = kosik.rename(columns={"kosik_item": "item"})
rohlik = rohlik.rename(columns={"rohlik_item": "item"})

In [10]:
full = (
    billa
    .merge(lidl, on="item", how="outer")
    .merge(kosik, on="item", how="outer")
    .merge(rohlik, on="item", how="outer")
)

In [11]:
full.head()

,item,billa_title,billa_price_czk,billa_packaging,billa_price_per_unit,lidl_title,lidl_price_czk,lidl_packaging,lidl_price_per_unit,kosik_title,kosik_price_czk,kosik_packaging,kosik_price_per_unit,rohlik_title,rohlik_price_czk,rohlik_packaging,rohlik_price_per_unit
0,banany,CORNY proteinová tyčinka 30% banán 50g,51.9,50 g,1.038000,NaN,NaN,NaN,NaN,"Banán, 1 ks",6.783,170.0 g,0.039900,Banán 1 ks,6.95,cca 190 g,0.036579
1,cervena_cocka,BILLA Čočka červená 500g,29.9,500 g,0.059800,NaN,NaN,NaN,NaN,Fine Life Čočka červená,34.900,500.0 g,0.069800,Kitchin Červená čočka,33.90,500 g,0.067800
2,cesnek,"Česká Farma Česnek síťka, 200g",49.9,200 g,0.249500,Česnek,39.9,NaN,NaN,Česnek drcený porce,64.900,1.0 kg,0.064900,"Česnek ""ošklivák"" český, síť",69.90,350 g,0.199714
3,chleb,"Chléb Chalupářský, 850g kulatý",58.9,850 g,0.069294,Dřevorubecký chléb,23.9,405 g,0.059012,Český pekař Chléb konzumní,42.500,1.2 kg,0.035417,Merhautovo pekařství Chléb žitný,35.90,400 g,0.089750
4,cibule,"Česká Farma Cibule 1kg, síť",20.9,1 kg,0.020900,NaN,NaN,NaN,NaN,"Cibule žlutá, síť",19.900,1.0 kg,0.019900,"Cibule žlutá, síť",19.90,1 kg,0.019900

In [12]:
full["item"]

0               banany
1        cervena_cocka
2               cesnek
3                chleb
4               cibule
5               jogurt
6                 kava
7          kureci_prsa
8                maslo
9                mleko
10    mrazena_zelenina
11       ovesne_vlocky
12        ovesny_napoj
13             paprika
14               pesto
15    rajcatova_omacka
16        repkovy_olej
17                ryze
18        sojovy_napoj
19             spagety
20           syr_eidam
21                tofu
22               tunak
23               vejce
Name: item, dtype: object

In [13]:
item_translation = {
    "banany": "bananas",
    "cervena_cocka": "red lentils",
    "cesnek": "garlic",
    "chleb": "bread",
    "cibule": "onion",
    "jogurt": "yogurt",
    "kava": "coffee",
    "kureci_prsa": "chicken breast",
    "maslo": "butter",
    "mleko": "milk",
    "mrazena_zelenina": "frozen vegetables",
    "ovesne_vlocky": "oat flakes",
    "ovesny_napoj": "oat drink",
    "paprika": "bell pepper",
    "pesto": "pesto",
    "rajcatova_omacka": "tomato sauce",
    "repkovy_olej": "rapeseed oil",
    "ryze": "rice",
    "sojovy_napoj": "soy drink",
    "spagety": "spaghetti",
    "syr_eidam": "edam cheese",
    "tofu": "tofu",
    "tunak": "tuna",
    "vejce": "eggs"
}

In [14]:
full = full.rename(columns={"item": "item_czech"})
full.insert(1, "item", full["item_czech"].map(item_translation))

In [15]:
full

,item_czech,item,billa_title,billa_price_czk,billa_packaging,billa_price_per_unit,lidl_title,lidl_price_czk,lidl_packaging,lidl_price_per_unit,kosik_title,kosik_price_czk,kosik_packaging,kosik_price_per_unit,rohlik_title,rohlik_price_czk,rohlik_packaging,rohlik_price_per_unit
0,banany,bananas,CORNY proteinová tyčinka 30% banán 50g,51.90,50 g,1.038000,NaN,NaN,NaN,NaN,"Banán, 1 ks",6.783,170.0 g,0.039900,Banán 1 ks,6.95,cca 190 g,0.036579
1,cervena_cocka,red lentils,BILLA Čočka červená 500g,29.90,500 g,0.059800,NaN,NaN,NaN,NaN,Fine Life Čočka červená,34.900,500.0 g,0.069800,Kitchin Červená čočka,33.90,500 g,0.067800
2,cesnek,garlic,"Česká Farma Česnek síťka, 200g",49.90,200 g,0.249500,Česnek,39.9,NaN,NaN,Česnek drcený porce,64.900,1.0 kg,0.064900,"Česnek ""ošklivák"" český, síť",69.90,350 g,0.199714
3,chleb,bread,"Chléb Chalupářský, 850g kulatý",58.90,850 g,0.069294,Dřevorubecký chléb,23.9,405 g,0.059012,Český pekař Chléb konzumní,42.500,1.2 kg,0.035417,Merhautovo pekařství Chléb žitný,35.90,400 g,0.089750
4,cibule,onion,"Česká Farma Cibule 1kg, síť",20.90,1 kg,0.020900,NaN,NaN,NaN,NaN,"Cibule žlutá, síť",19.900,1.0 kg,0.019900,"Cibule žlutá, síť",19.90,1 kg,0.019900
5,jogurt,yogurt,clever Jogurt bílý s bifidokulturou 500g,22.90,500 g,0.045800,Bílý jogurt,17.9,300 g,0.059667,"ARO Jogurt bílý 1,5% tuku",19.900,400.0 g,0.049750,Hollandia Nízkotučný jogurt bílý,17.90,380 g,0.047105
6,kava,coffee,Tira Crema pražená mletá káva 250g,79.90,250 g,0.319600,NaN,NaN,NaN,NaN,Casino Káva mletá BRASIL,119.900,250.0 g,0.479600,Ubomi Intense RFA mletá káva,84.90,250 g,0.339600
7,kureci_prsa,chicken breast,VOCÍLKA Kuřecí prsní řízky premium,259.90,1 kg,0.259900,BIO Kuřecí prsní řízky,59.9,Dostupné pouze ve vybraných prodejnách,NaN,Fine Life Kuřecí prsní řízky,94.900,500.0 g,0.189800,Kuřecí prsní řízky od českého výrobce XXL balení,263.88,"cca 1,2 kg",0.219900
8,maslo,butter,Milkpol Máslo 82% 250 g,39.90,250 g,0.159600,Perla Margarín s máslovou příchutí 39% tuku,34.9,450 g,0.077556,Tatra Farmářské máslo (84%),34.900,200.0 g,0.174500,Miil Máslo 82%,44.90,250 g,0.179600
9,mleko,milk,"clever Mléko polotučné trvanlivé 1,5 % tuku 1l",12.90,1 l,0.012900,"Trvanlivé mléko 1,5%",12.9,1 l,0.012900,"Fine Life Polotučné trvanlivé mléko 1,5%",9.900,1.0 l,0.009900,"Miil Trvanlivé polotučné mléko 1,5%",14.90,1 l,0.014900
10,mrazena_zelenina,frozen vegetables,clever Zeleninová směs podsvíčková 450g,19.90,450 g,0.044222,NaN,NaN,NaN,NaN,ARO Zeleninová směs pod svíčkovou,19.900,400.0 g,0.049750,Agro Jesenice Zelenina s kukuřicí,20.90,350 g,0.059714
11,ovesne_vlocky,oat flakes,clever Ovesné vločky celozrnné 500g,13.90,500 g,0.027800,Ovesné vločky hrub,11.9,500 g,0.023800,Vločkárna Vřesce Ovesné vločky,21.900,450.0 g,0.048667,Yutto Celozrnné ovesné vločky extra jemné,11.90,500 g,0.023800
12,ovesny_napoj,oat drink,BILLA BIO Ovesný nápoj 1l,33.90,1 l,0.033900,NaN,NaN,NaN,NaN,Metro Chef BIO Nápoj ovesný,35.900,1.0 l,0.035900,Yutto BIO Ovesný nápoj,27.90,1 l,0.027900
13,paprika,bell pepper,"Bon Via Paprika mix barev 500g, balení",59.90,500 g,0.119800,NaN,NaN,NaN,NaN,"Paprika bílá, 1 ks",9.490,100.0 g,0.094900,Paprika žlutá 1 ks,20.54,cca 210 g,0.097810
14,pesto,pesto,clever Bazalkové pesto 190g,29.90,190 g,0.157368,NaN,NaN,NaN,NaN,Casino Bazalkové pesto,64.900,190.0 g,0.341579,Kitchin Bazalkové pesto alla Genovese,37.90,190 g,0.199474
15,rajcatova_omacka,tomato sauce,Franz Josef Kaiser Exclusive Napoletana rajčat...,44.90,350 g,0.128286,NaN,NaN,NaN,NaN,Mutti Omáčka rajčatová na pizzu+bylinky,47.900,400.0 g,0.119750,Kitchin Pečené fazole v rajčatové omáčce,19.90,420 g,0.047381
16,repkovy_olej,rapeseed oil,clever Řepkový olej 1l,34.90,1 l,0.034900,Řepkový olej,34.9,1 l,0.034900,Fabio Manka řepkový olej,54.900,1.0 l,0.054900,Kitchin Řepkový olej,34.90,1 l,0.034900
17,ryze,rice,BILLA Dlouhozrnná rýže loupaná 1000g,44.90,1 kg,0.044900,NaN,NaN,NaN,NaN,ARO Rýže dlouhozrnná parboiled,34.900,1.0 kg,0.034900,Kitchin Rýže dlouhozrnná,29.90,1 kg,0.029900
18,sojovy_napoj,soy drink,BILLA BIO Sójový nápoj 1l,33.90,1 l,0.033900,NaN,NaN,NaN,NaN,Metro Chef BIO Nápoj sójový,48.900,1.0 l,0.048900,Yutto BIO Sójový nápoj,29.90,1 l,0.029900
19,spagety,spaghetti,Franz Josef Kaiser Exclusive Špagety 500g,29.90,500 g,0.059800,Špagety,11.9,500 g,0.023800,ARO Špagety bezvaječné,12.900,500.0 g,0.025800,Špagety,12.90,400 g,0.032250
20,syr_eidam,edam cheese,clever Eidam bloček 30% 250g,44.90,250 g,0.179600,PILOS Eidam,9.9,NaN,NaN,Fine Life Eidam 30 % bloček,35.900,200.0 g,0.179500,Miil Eidam 30% bloček,44.90,250 g,0.179600
21,tofu,tofu,LUNTER Naturální tofu 180g,22.90,180 g,0.127222,NaN,NaN,NaN,NaN,Lunter Tofu natural,23.900,180.0 g,0.132778,SoYum Tofu,60.90,450 g,0.135333
22,tunak,tuna,Tuňák přírodní Vier Diamanten 195 g,77.82,195 g,0.399077,Tuňák žlutoploutvý,39.9,cena za 100 g,0.399000,Giana Tuňák drcený ve vlastní šťávě,37.900,170.0 g,0.222941,Kitchin Tuňák celý ve slunečnicovém oleji,52.90,195 g,0.271282
23,vejce,eggs,BILLA Čerstvá vejce L 6 ks,34.90,6 ks,5.816667,NaN,NaN,NaN,NaN,"Vejce Kosičky Čerstvá podestýlková vejce, vel. M",79.900,10.0 ks,NaN,Pohodová vejce Podestýlková L,45.90,6 ks,7.650000

In [16]:
basket_items = []

for idx, row in full.iterrows():
    item_name = row['item']
    
    # Collect BOTH prices and per-unit prices from all stores
    stores = {
        'billa': {
            'price': row['billa_price_czk'],
            'per_unit': row['billa_price_per_unit']
        },
        'lidl': {
            'price': row['lidl_price_czk'],
            'per_unit': row['lidl_price_per_unit']
        },
        'kosik': {
            'price': row['kosik_price_czk'],
            'per_unit': row['kosik_price_per_unit']
        },
        'rohlik': {
            'price': row['rohlik_price_czk'],
            'per_unit': row['rohlik_price_per_unit']
        }
    }
    
    # Filter out stores with NaN prices
    valid_stores = {
        store: data for store, data in stores.items() 
        if pd.notna(data['per_unit'])
    }
    
    if not valid_stores:
        print(f"{item_name}: NO PRICES AVAILABLE")
        continue
    
    # Find cheapest by PER_UNIT price
    cheapest_store = min(valid_stores, key=lambda s: valid_stores[s]['per_unit'])
    cheapest_actual_price = valid_stores[cheapest_store]['price']
    cheapest_per_unit = valid_stores[cheapest_store]['per_unit']
    
    print(f"{item_name:20} - {cheapest_store:8}: {cheapest_actual_price:.2f} CZK (per unit: {cheapest_per_unit:.6f})")
    
    basket_items.append({
        'item': item_name,
        'unit_price': cheapest_actual_price,  # ← ACTUAL PRICE YOU PAY
        'store': cheapest_store
    })

# Convert to DataFrame
basket_df = pd.DataFrame(basket_items)

bananas              - rohlik  : 6.95 CZK (per unit: 0.036579)
red lentils          - billa   : 29.90 CZK (per unit: 0.059800)
garlic               - kosik   : 64.90 CZK (per unit: 0.064900)
bread                - kosik   : 42.50 CZK (per unit: 0.035417)
onion                - kosik   : 19.90 CZK (per unit: 0.019900)
yogurt               - billa   : 22.90 CZK (per unit: 0.045800)
coffee               - billa   : 79.90 CZK (per unit: 0.319600)
chicken breast       - kosik   : 94.90 CZK (per unit: 0.189800)
butter               - lidl    : 34.90 CZK (per unit: 0.077556)
milk                 - kosik   : 9.90 CZK (per unit: 0.009900)
frozen vegetables    - billa   : 19.90 CZK (per unit: 0.044222)
oat flakes           - lidl    : 11.90 CZK (per unit: 0.023800)
oat drink            - rohlik  : 27.90 CZK (per unit: 0.027900)
bell pepper          - kosik   : 9.49 CZK (per unit: 0.094900)
pesto                - billa   : 29.90 CZK (per unit: 0.157368)
tomato sauce         - rohlik  : 19.90 CZK (per unit: 0.047381)
rapeseed oil         - billa   : 34.90 CZK (per unit: 0.034900)
rice                 - rohlik  : 29.90 CZK (per unit: 0.029900)
soy drink            - rohlik  : 29.90 CZK (per unit: 0.029900)
spaghetti            - lidl    : 11.90 CZK (per unit: 0.023800)
edam cheese          - kosik   : 35.90 CZK (per unit: 0.179500)
tofu                 - billa   : 22.90 CZK (per unit: 0.127222)
tuna                 - kosik   : 37.90 CZK (per unit: 0.222941)
eggs                 - billa   : 34.90 CZK (per unit: 5.816667)

In [17]:
# Define monthly quantities
quantities = {
    "bananas": 12,
    "red lentils": 1,
    "garlic": 1,
    "bread": 4,
    "onion": 8,
    "yogurt": 10,
    "coffee": 1,
    "chicken breast": 4,
    "butter": 1,
    "milk": 4,
    "frozen vegetables": 3,
    "oat flakes": 1,
    "oat drink": 4,
    "bell pepper": 4,
    "pesto": 1,
    "tomato sauce": 4,
    "rapeseed oil": 1,
    "rice": 2,
    "soy drink": 4,
    "spaghetti": 4,
    "edam cheese": 2,
    "tofu": 2,
    "tuna": 2,
    "eggs": 2
}

In [18]:
# Calculate monthly costs
basket_df['qty_per_month'] = basket_df['item'].map(quantities)
basket_df['monthly_cost'] = basket_df['unit_price'] * basket_df['qty_per_month']

print("MONTHLY GROCERY BASKET (Cheapest Option Per Item)")
print(basket_df[['item', 'unit_price', 'qty_per_month', 'monthly_cost']].to_string())

total = basket_df['monthly_cost'].sum()
print(f"TOTAL MONTHLY COST: {total:.2f} CZK")

MONTHLY GROCERY BASKET (Cheapest Option Per Item)
                 item  unit_price  qty_per_month  monthly_cost
0             bananas        6.95             12         83.40
1         red lentils       29.90              1         29.90
2              garlic       64.90              1         64.90
3               bread       42.50              4        170.00
4               onion       19.90              8        159.20
5              yogurt       22.90             10        229.00
6              coffee       79.90              1         79.90
7      chicken breast       94.90              4        379.60
8              butter       34.90              1         34.90
9                milk        9.90              4         39.60
10  frozen vegetables       19.90              3         59.70
11         oat flakes       11.90              1         11.90
12          oat drink       27.90              4        111.60
13        bell pepper        9.49              4         37.96
14              pesto       29.90              1         29.90
15       tomato sauce       19.90              4         79.60
16       rapeseed oil       34.90              1         34.90
17               rice       29.90              2         59.80
18          soy drink       29.90              4        119.60
19          spaghetti       11.90              4         47.60
20        edam cheese       35.90              2         71.80
21               tofu       22.90              2         45.80
22               tuna       37.90              2         75.80
23               eggs       34.90              2         69.80
TOTAL MONTHLY COST: 2126.16 CZK

In [19]:
basket_df

                 item  unit_price   store  qty_per_month  monthly_cost
0             bananas        6.95  rohlik             12         83.40
1         red lentils       29.90   billa              1         29.90
2              garlic       64.90   kosik              1         64.90
3               bread       42.50   kosik              4        170.00
4               onion       19.90   kosik              8        159.20
5              yogurt       22.90   billa             10        229.00
6              coffee       79.90   billa              1         79.90
7      chicken breast       94.90   kosik              4        379.60
8              butter       34.90    lidl              1         34.90
9                milk        9.90   kosik              4         39.60
10  frozen vegetables       19.90   billa              3         59.70
11         oat flakes       11.90    lidl              1         11.90
12          oat drink       27.90  rohlik              4        111.60
13        bell pepper        9.49   kosik              4         37.96
14              pesto       29.90   billa              1         29.90
15       tomato sauce       19.90  rohlik              4         79.60
16       rapeseed oil       34.90   billa              1         34.90
17               rice       29.90  rohlik              2         59.80
18          soy drink       29.90  rohlik              4        119.60
19          spaghetti       11.90    lidl              4         47.60
20        edam cheese       35.90   kosik              2         71.80
21               tofu       22.90   billa              2         45.80
22               tuna       37.90   kosik              2         75.80
23               eggs       34.90   billa              2         69.80

In [20]:
output_path_basket = os.path.join('..', 'data', 'clean', 'groceries_basket.csv')
basket_df.to_csv(output_path_basket, index=False)

In [21]:
output_path = os.path.join('..', 'data', 'clean', 'groceries_full.csv')
full.to_csv(output_path, index=False)